richford/groupyr

README.md

Small change to the funding info to better reflect which grant is funding what activity.

Replaces CRCNS grant with our BRAINI grant in README

---

.github/CONTRIBUTING.md
groupyr/datasets.py
groupyr/logistic.py
groupyr/tests/test_datasets.py

Resolves #14 
Resolves #15 
This PR shuffles the groups in `make_group_regression`, uses `generator.choice` instead of `np.random.choice`, and adds tests to detect these bugs in the future.

FIX: Shuffle groups make_group_regression. Use `generator.choice` in make_group_classification

---

.github/CONTRIBUTING.md
.gitignore
.maintenance/publish_release.sh
.maintenance/update_zenodo.py
.zenodo.json
setup.cfg

This PR
- updates the .zenodo.json file.
- adds the automatic zenodo update script to the publish script.
- adds a CREATORS_FIRST parameter to the automatic zenodo update script
- adds a `maint` install option which includes `rapidfuzz`. Maintainers will still have to install `git-extras` on their own.
- adds `line-contributors.txt` to `.gitignore`.

MAINT: Automatically update zenodo file as part of release script

---

.github/CONTRIBUTING.md
.github/workflows/docbuild.yml
.github/workflows/test.yml
examples/plot_classifier.py
groupyr/tests/test_datasets.py
groupyr/tests/test_sgl.py

This PR uses `python -m pip` over `pip` for reasons that I link to in the updated `CONTRIBUTING.md`.
It also switches all `random_state=42` to `random_state=1729`, which is the second [taxicab number](https://en.wikipedia.org/wiki/Taxicab_number).

STY: Prefer `python -m pip` over `pip`. Also use taxicab random_state instead of 42

---

.github/CONTRIBUTING.md
groupyr/_prox.py
groupyr/logistic.py
groupyr/sgl.py
groupyr/tests/test_prox.py

This commit speeds up the SparseGroupsL1.prox() method. I ran lprun on the previous method with test data from make_group_regression. This yielded
```
Hits         Time  Per Hit   % Time  Line Contents
==================================================
1187        643.0      0.5      0.2          norms = (
2374     265686.0    111.9     80.3              np.array([np.linalg.norm(l1_prox[grp]) for grp in self.groups])
1187        940.0      0.8      0.3              / self.group_scale
)
```
I realized that a lot of time could be saved by vectorizing the group norms, but also recognized the contraint that groups may be of different sizes so one can't simply use `np.linalg.norm` along one axis (since a split `l1_prox` array would be ragged). So I created a group mask matrix in ``__init__`` …

ENH: Speed up `SparseGroupL1.prox()`

---

groupyr/sgl.py
groupyr/tests/test_sgl.py

Small (and not particularly important) follow up to #31. Just making sure that the code does what the documentation says in this case. Otherwise, this throws an `AttributeError` on access to this attribute.

Sets bayes_optimizer_ to None when "grid" strategy is used

---

groupyr/logistic.py
groupyr/sgl.py

This PR assigns an `error_score` parameter to `BayesSearchCV` so that the optimizer doesn't fail if the estimator fails to fit.

FIX: Assign error_score in BayesSearchCV

---

paper/paper.bib
paper/paper.md

Resolves an issue brought up in [this comment](https://github.com/openjournals/joss-reviews/issues/3024#issuecomment-779410921) in the joss review thread. Thanks @janfreyberg!
There isn't really a DOI for the group-lasso reference so I kind of improvised with how to cite a GitHub repo.

ENH: Add lightning and group-lasso citations to paper

---

paper/paper.bib
paper/paper.md

This PR adds author contributions using the [CRediT taxonomy](http://dx.doi.org/10.1087/20150211).
@arokem, @mnarayan, @jyeatman, @nrs02004, please review and approve my description of the author contributions.
It also refines many of the bibtex entries for our references, adding DOIs where possible.

DOC: Add author contributions using the CRediT taxonomy

---

.gitignore
examples/compare_group_lasso_performance.py
paper/paper.md

This PR adds an example with a rudimentary performance comparison between the group-lasso package and groupyr.

DOC: Add groupyr/group-lasso comparison example

---

.github/workflows/test.yml
Makefile
groupyr/logistic.py
setup.cfg
tox.ini

Inspired by [this pyAFQ PR](https://github.com/yeatmanlab/pyAFQ/pull/636), this PR loosens groupyr's dependency requirements.

DEP: Loosen dependency requirements

---

.github/workflows/docbuild.yml

This PR restricts docs publication to gh-pages to only Python 3.8. Previous doc builds were failing because of conflicting simultaneous pushes to gh-pages.

CI: Only publish docs to GitHub pages for one Python version

---

groupyr/tests/test_transform.py
groupyr/transform.py

Resolves #50 
WIP until I add all of the transformers.
Also, these transformers currently take indices of groups to extract/remove. We should optionally allow the user to pass a feature name to select or remove. We could then check the feature name against elements of the feature column names (provided as another kwarg or taken from `DataFrame.columns` if `X` is a dataframe). That way, the user wouldn't have to remember which group index corresponds to the CST, for example.

ENH: Add group transformers

---

.github/workflows/test.yml
groupyr/decomposition.py
groupyr/tests/test_common.py
groupyr/tests/test_decomposition.py
groupyr/utils.py
setup.cfg
tox.ini

This PR adds a group-wise functional FPCA transformer. It computes functional PCA for each group (excluding the groups specified by the user on init) during `fit`. And then transforms into the lower dimensional PC space during `transform`.
It is a WIP because I haven't added tests.

ENH: Add GroupFPCA

---

groupyr/decomposition.py
groupyr/tests/test_decomposition.py
tox.ini

This PR adds a GroupPCA transformer. The pre-existing GroupFPCA only works for functional data. These new transformers perform standard PCA in each group. This PR also adds supervised PCA models.

Add GroupPCA, and supervised PCA variants

---

groupyr/tests/test_transform.py
groupyr/transform.py

This PR adds a `select_intersection` parameter to `GroupShuffler`, `GroupExtractor`, and `GroupRemover`. Previously, if you passed a sequence of group labels to any of these transformers, it would return the union of group labels. Now, if you pass `select_intersection=True`, it will return the intersection of the labels.
Resolves #60

ENH: Add select_intersection kwarg to transformers

---

groupyr/decomposition.py
groupyr/tests/test_decomposition.py
groupyr/tests/test_transform.py
groupyr/tests/test_utils.py
groupyr/transform.py
groupyr/utils.py

Resolves #63
This PR adds a `get_feature_names` method to most of the transformers and the PCA classes.

Add get_feature_names to transformers and PCA classes

---

.github/workflows/docbuild.yml
.github/workflows/test.yml
groupyr/logistic.py
groupyr/sgl.py
groupyr/tests/test_sgl.py

Potentially closes #65.
I noticed that `param__alpha` is also used [here](https://github.com/richford/groupyr/blob/main/groupyr/logistic.py#L1141) (in "logistic.py"). Do we need to change it there as well? Also, any suggestions for testing?

Change the key name to only have one underscore.

---

groupyr/datasets.py

Resolves #71 by limiting the verbatim quotation of sklearn's sample generators.

Limit verbatim quotation in documentation of sample generators

---

groupyr/logistic.py
groupyr/sgl.py

This PR fixes an import error in newer versions of sklearn but removing the `_joblib_parallel_args` functions and passing `prefer` directly to `joblib.Parallel`.

BF: Update joblib parallel args

---

setup.cfg

This complicates the installation of AFQ-Insight, and hardly seems necessary.

Don't pin the numpy version.
