richford/groupyr

- .github/workflows/test.yml
- Makefile
- README.md
- groupyr/__init__.py
- groupyr/_base.py
- groupyr/_prox.py
- groupyr/datasets.py
- groupyr/logistic.py
- groupyr/sgl.py
- groupyr/tests/test_common.py
- groupyr/tests/test_sgl.py
- groupyr/utils.py
- setup.cfg
- setup.py
This PR edits the GitHub Actions workflow in `test.yml` to add a `pydocstyle` test. Afterward, all docstrings will have to conform to the nummpy docstring standard.
This PR also fixes the coverage upload to coveralls.io
> CI: Use pydocstyle in github actions

- .github/CONTRIBUTING.md
This PR adds a CI pull request example to CONTRIBUTING.md and a self-reference as a DOC pull request example.
> DOC: Add pull request examples to CONTRIBUTING.md

- .github/CONTRIBUTING.md
- groupyr/tests/test_utils.py
- groupyr/utils.py
This PR increases test coverage in `utils.py` by testing the `check_groups` function.
> TST: Test check_groups in utils.py

- groupyr/_base.py
- groupyr/_prox.py
- groupyr/datasets.py
- groupyr/logistic.py
- groupyr/sgl.py
- groupyr/tests/test_sgl.py
This PR tests the sparsity mask and chosen groups/features attributes in `_base.py`. It also removes the `@registered` decorator.
> TST: Test sparsity masks and chosen groups/features in _base.py

- groupyr/_base.py
- groupyr/logistic.py
- groupyr/sgl.py
- groupyr/tests/test_sgl.py
This PR
- removes sparse matrix support
- adds no cover pragmas for verbosity conditionals
- add input validation tests for `_alpha_grid` and `SGLCV`
> TST: Add tests for `SGL`, `SGLCV`, etc.

- groupyr/logistic.py
> FIX: Use classifier=True in check_cv for LogisticSGLCV

- doc/conf.py
> DOC: Fix mathjax rendering in documentation

- .coveragerc
- groupyr/logistic.py
- groupyr/sgl.py
- groupyr/tests/test_sgl.py
- setup.cfg
> ENH: Add BayesSearchCV option to SGLCV and LogisticSGLCV

- groupyr/logistic.py
- groupyr/sgl.py
> ENH: Use sgl_scoring_path instead of sklearn's _path_residuals

- paper/paper.bib
Addresses https://github.com/openjournals/joss-reviews/issues/3016#issuecomment-775608090
> Remove redundant paper reference

- setup.cfg
Resolves #39. Thanks @janfreyberg
> DEP: remove ipywidgets from setup.cfg dependencies

- Makefile
Partially resolves an issue raised by JOSS reviewer [here](https://github.com/openjournals/joss-reviews/issues/3024#issuecomment-780529365)
> DOC: Add help target to makefile to make is self-documenting

- doc/install.rst
- setup.cfg
And add a list of dependencies to the installation directions.
> Move matplotlib dependency to dev option

- doc/api.rst
- examples/plot_sgl_path.py
> Add sgl_path example to the documentation

- doc/api.rst
- groupyr/tests/test_transform.py
- groupyr/transform.py
Addresses an issue raised in a related AFQ-Insight issue: https://github.com/richford/AFQ-Insight/issues/78
Ported here because it is not specific to tractometry.
> ENH: Add GroupAggregator, tests, and doc API

- doc/api.rst
- groupyr/tests/test_transform.py
- groupyr/transform.py
This PR adds a group-wise resampling transformer and tests.
> ENH: Add GroupResampler

- examples/plot_balanced_classifier.py
- groupyr/sgl.py
- groupyr/tests/test_sgl.py
and add an example for F1 scoring in Logistic SGLCV.
Resolves #67
> Add scoring param to SGLCV

- .github/workflows/test.yml
- setup.cfg
Do we also need to add this to the CI somewhere?
> Add an "all" installation rule.

- .github/workflows/test.yml
- groupyr/sgl.py
- setup.cfg
Trying to resolve issues that have come up on this PR: https://github.com/yeatmanlab/AFQ-Insight/pull/138
> Resolve dependency versions 

- groupyr/_base.py
- setup.cfg
I think we need to do this to help with https://github.com/yeatmanlab/AFQ-Insight/pull/138
> Update copt to most recent.

- .github/workflows/docbuild.yml
- .github/workflows/test.yml
- groupyr/tests/test_transform.py
- setup.cfg
- tox.ini
Based on https://scientific-python.org/specs/spec-0000/
> Upgrades Python support 
